/* (c) 2019 Confio UO. Licensed under Apache-2.0 */

/* Generated with cbindgen:0.14.4 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct cache_t {

} cache_t;

void greet(const char *name);

cache_t *init_cache(void);

void run_with_standalone(const char *vm_kind_c,
                         const char *context_c,
                         const char *context_file_c,
                         const char *input_c,
                         const char *state_c,
                         const char *method_name_c,
                         const char *config_c,
                         const char *config_file_c,
                         const char *wasm_file_c);
